BASE_URL = "https://djinni.co/jobs/?primary_keyword=Python"

ORDERED_DAYS = ['Monday',
                'Tuesday',
                'Wednesday',
                'Thursday',
                'Friday',
                'Saturday',
                'Sunday']

TECHNOLOGIES = ['Python',
                'Django',
                'Flask',
                'FastAPI',
                'AWS',
                'Azure',
                'Git',
                'SQL',
                'REST',
                'JavaScript',
                'HTML',
                'CSS',
                'React',
                'Vue.js',
                'Angular',
                'Celery',
                'Docker',
                'Kubernetes',
                'PostgreSQL',
                'MySQL',
                'SQLite',
                'MongoDB',
                'Redis',
                'GraphQL',
                'CI/CD',
                'Jenkins',
                'CircleCI',
                'pytest',
                'unittest',
                'WebSockets',
                'OAuth',
                'JSON Web Tokens',
                'JWT',
                'RabbitMQ',
                'Elasticsearch',
                'Caching strategies',
                'Beautiful Soup',
                'Scrapy',
                'GraphQL',
                'scikit-learn',
                'TensorFlow',
                'PyTorch',
                'pandas',
                'NumPy',
                'Beautiful Soup',
                'Scrapy',
                'JIRA',
                'GitHub',
                'GitLab']
